<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function invitationList($id){
		$conn = $this->getEntityManager()
            ->getConnection();
        $sql = '
            SELECT id, name
            FROM user
            WHERE id != :id
            ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(array('id' => $id));
        //var_dump($stmt->fetchAll());

        return $stmt->fetchAll();
	}
}
